services:
  
  client:
    build:
      context: .
      dockerfile: dockerfile-client
    command: >
      python
      client.py
    volumes:
      - .:/code

  server:
    build:
      context: .
      dockerfile: dockerfile-server
    command: >
      python
      server.py
    ports:
      - 9090:9090
    volumes:
      - .:/code
  